### PR TITLE
Recreate associations when the id of a model changes

### PR DESCRIPTION
**Pull request by joostverdoorn**
@rogierslag please review

### CODE REVIEW

**Comment by rogierslag** [comment]
:+1:

**Comment by steffansluis** [comment]
@joostverdoorn I'm guessing this has to do with syncing back the new id when creating a model? Otherwise, why would the id change?

**Comment by rogierslag** [comment]
When persisting an entity, the id changes (a new one didnt have an id before)

**Comment by joostverdoorn** [comment]
Yes indeed. Saving a new model is (should be) the only time this happens

**Pull request merged**
